// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz8P2iTAk8Ys1DNccA9R3b_kuqEm3t8N4',
    appId: '1:720236048832:web:8e58bdc841154d7e841825',
    messagingSenderId: '720236048832',
    projectId: 'skaly-f85ff',
    authDomain: 'skaly-f85ff.firebaseapp.com',
    storageBucket: 'skaly-f85ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAngTdUAUMbpr9zG9wbvyTU6yyfDvJXvhE',
    appId: '1:720236048832:android:aa1dd29c06b6e0cd841825',
    messagingSenderId: '720236048832',
    projectId: 'skaly-f85ff',
    storageBucket: 'skaly-f85ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBidHw3Z___YlV9etwY3b28yzKuFTkZ2og',
    appId: '1:720236048832:ios:95678f250e7dfdf7841825',
    messagingSenderId: '720236048832',
    projectId: 'skaly-f85ff',
    storageBucket: 'skaly-f85ff.appspot.com',
    iosBundleId: 'com.skaly.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBidHw3Z___YlV9etwY3b28yzKuFTkZ2og',
    appId: '1:720236048832:ios:79695558c0c43acd841825',
    messagingSenderId: '720236048832',
    projectId: 'skaly-f85ff',
    storageBucket: 'skaly-f85ff.appspot.com',
    iosBundleId: 'com.skaly.gym.RunnerTests',
  );
}
